project:
  type: website

website:
  title: "Felipe Marques"
  navbar:
    right:
      - href: index.qmd
        text: Início
      - href: about.qmd
        text: Sobre
      - href: janelas/projects.qmd
        text: Projetos
      - href: janelas/studies.qmd
        text: Estudos
format:
  html:
    theme: flatly
    css: styles.css
    toc: false
